"""Verification upd  

Revision ID: 1489c65f56b3
Revises: 4bdfc6368052
Create Date: 2025-12-09 10:19:54.621110

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1489c65f56b3'
down_revision: str | Sequence[str] | None = '4bdfc6368052'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issued_registration', sa.Column('token', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issued_registration', 'token')
    # ### end Alembic commands ###
