"""Initial  

Revision ID: 1dd5c68f219a
Revises: 
Create Date: 2025-11-24 23:08:49.487003

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd5c68f219a'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BOT', name='leadsourcetypeenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='operatorstatusenum'), nullable=False),
    sa.Column('active_appeals_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', name='appealstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('lead_source_id', sa.Integer(), nullable=False),
    sa.Column('assigned_operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['lead_source_id'], ['lead_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_source_operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_factor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('lead_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_source_id'], ['lead_source.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_source_operator')
    op.drop_table('appeal')
    op.drop_table('operator')
    op.drop_table('lead_source')
    op.drop_table('lead')
    # ### end Alembic commands ###
