"""User full name  

Revision ID: 5f65ceaa5196
Revises: d4e272feaf5d
Create Date: 2025-12-09 08:43:54.580600

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f65ceaa5196'
down_revision: str | Sequence[str] | None = 'd4e272feaf5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
