"""Upd FKs  

Revision ID: 7f57fb756f97
Revises: ceac1d697554
Create Date: 2025-12-10 01:54:38.162804

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f57fb756f97'
down_revision: str | Sequence[str] | None = 'ceac1d697554'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_participant_user_id_fkey'), 'event_participant', type_='foreignkey')
    op.create_foreign_key(None, 'event_participant', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint(op.f('instant_notification_recipient_id_fkey'), 'instant_notification', type_='foreignkey')
    op.create_foreign_key(None, 'instant_notification', 'user', ['recipient_id'], ['id'], ondelete='cascade')
    op.drop_constraint(op.f('issued_login_recovery_user_id_fkey'), 'issued_login_recovery', type_='foreignkey')
    op.create_foreign_key(None, 'issued_login_recovery', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint(op.f('login_session_user_id_fkey'), 'login_session', type_='foreignkey')
    op.create_foreign_key(None, 'login_session', 'user', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'login_session', type_='foreignkey')
    op.create_foreign_key(op.f('login_session_user_id_fkey'), 'login_session', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'issued_login_recovery', type_='foreignkey')
    op.create_foreign_key(op.f('issued_login_recovery_user_id_fkey'), 'issued_login_recovery', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'instant_notification', type_='foreignkey')
    op.create_foreign_key(op.f('instant_notification_recipient_id_fkey'), 'instant_notification', 'user', ['recipient_id'], ['id'])
    op.drop_constraint(None, 'event_participant', type_='foreignkey')
    op.create_foreign_key(op.f('event_participant_user_id_fkey'), 'event_participant', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
