"""Initial  

Revision ID: 8e971abc9753
Revises: 
Create Date: 2025-12-09 14:29:30.180598

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e971abc9753'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'INACTIVE', name='operatorstatusenum').create(op.get_bind())
    sa.Enum('BOT', name='leadsourcetypeenum').create(op.get_bind())
    sa.Enum('ACTIVE', 'RESOLVED', name='appealstatusenum').create(op.get_bind())
    sa.Enum('USER', 'ADMINISTRATOR', name='userroleenum').create(op.get_bind())
    op.create_table('issued_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('verification_code', sa.Integer(), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('BOT', name='leadsourcetypeenum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', name='operatorstatusenum', create_type=False), nullable=False),
    sa.Column('active_appeals', sa.Integer(), nullable=False),
    sa.Column('active_appeals_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', postgresql.ENUM('USER', 'ADMINISTRATOR', name='userroleenum', create_type=False), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('appeal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'RESOLVED', name='appealstatusenum', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('lead_source_id', sa.Integer(), nullable=False),
    sa.Column('assigned_operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['lead_source_id'], ['lead_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issued_login_recovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('lead_source_operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routing_factor', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('lead_source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_source_id'], ['lead_source.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_session',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_session')
    op.drop_table('lead_source_operator')
    op.drop_table('issued_login_recovery')
    op.drop_table('appeal')
    op.drop_table('user')
    op.drop_table('operator')
    op.drop_table('lead_source')
    op.drop_table('lead')
    op.drop_table('issued_registration')
    sa.Enum('USER', 'ADMINISTRATOR', name='userroleenum').drop(op.get_bind())
    sa.Enum('ACTIVE', 'RESOLVED', name='appealstatusenum').drop(op.get_bind())
    sa.Enum('BOT', name='leadsourcetypeenum').drop(op.get_bind())
    sa.Enum('ACTIVE', 'INACTIVE', name='operatorstatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
