"""Add verification fields  

Revision ID: 9468aa2fe528
Revises: 5f65ceaa5196
Create Date: 2025-12-09 09:17:54.195936

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9468aa2fe528'
down_revision: str | Sequence[str] | None = '5f65ceaa5196'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('verification_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
