"""reminder_queued_at  

Revision ID: 9ee6e7350419
Revises: 7052a28e0ace
Create Date: 2025-12-09 23:25:36.666925

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee6e7350419'
down_revision: str | Sequence[str] | None = '7052a28e0ace'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participant', sa.Column('reminder_queued_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_participant', 'reminder_queued_at')
    # ### end Alembic commands ###
