"""Fix concurrency support in reference domain  

Revision ID: c70bc5e8abc2
Revises: 4a76550f1dde
Create Date: 2025-12-08 21:05:44.411487

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70bc5e8abc2'
down_revision: str | Sequence[str] | None = '4a76550f1dde'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator', sa.Column('active_appeals', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operator', 'active_appeals')
    # ### end Alembic commands ###
