"""Add cta fields to instant notifications  

Revision ID: ceac1d697554
Revises: 9ee6e7350419
Create Date: 2025-12-10 01:17:00.590051

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceac1d697554'
down_revision: str | Sequence[str] | None = '9ee6e7350419'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instant_notification', sa.Column('cta_url', sa.String(), nullable=True))
    op.add_column('instant_notification', sa.Column('cta_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instant_notification', 'cta_label')
    op.drop_column('instant_notification', 'cta_url')
    # ### end Alembic commands ###
